from Tkinter import *
from PIL import ImageTk,Image
fun=Tk()
fun.minsize(650,650)
fun.maxsize(650,650)
open_img=ImageTk.PhotoImage(Image.open("open.png"))
save_img=ImageTk.PhotoImage(Image.open("save.png"))
exit_img=ImageTk.PhotoImage(Image.open("exit.jpg"))
label_file_name=Label(fun,text="File Name")
label_file_name.place(relx=0.28,re;y=0.03,anchor=CENTER)
input_file_name=Entry(fun)
input_file_name.place(relx=0.46,rely=0.03,anchor=CENTER)
my_text=Text(fun,height=35,width=80)
my_text.place(relx=0.5,rely=0.55,anchor=CENTER)
name=""
def openfile():
    global name
    my_text.delete(1.0,END)
    input_file_name.delete(0,END)
    text_file=filedialog.askopenfilename(title="Open text file",filetypes=(("Text files","*txt"),))
    print(text_file)
    name=os.path.basename(text_file)
    formated_name.insert(END,formated_name)
    fun.title(formated_name)
    text_file=open(name."r")
    paragraph=text_file,read()
    my_text.insert(NED,paragraph)
    text_file.close()
def save():
    input_name=input_file_name.get()
    file=open(input_name,",txt","w")
    data=my_text.get("1.0",END)
    print(data)
    file.write(data)
    input_file_name.delete(0.END)
    my_text.delete(1.0,END)
    messagebox.showinfo("Update","Success")
def closeWindow():
    root.destroy()
open_button=Button(fun,image=open_img,text="Open file",command=openfile)
open_button.place(relx=0.05,rely=0.03,anchor=CENTER)
save_button=Button(fun,image=save_img,text="Save file",command=save)
save_button.place(relx=0.11,rely=0.03,anchor=CENTER)
exit_button=Button(fun,image=exit_img,text="Exit file",command=closeWindow)
exit_button.place(relx=0.17,rely=0.03,anchor=CENTER)
fun.mainloop()